# Copyright 2023 Authors of kubean-io
# SPDX-License-Identifier: Apache-2.0

---
- name: Get information about the cluster
  hosts: kube_control_plane[0]
  gather_facts: false
  become: true
  any_errors_fatal: "{{ any_errors_fatal | default(true) }}"
  tasks:
    - name: Get cluster info
      shell: |
        /usr/local/bin/kubectl get node -o wide
        /usr/local/bin/kubectl -n kube-system get pod
        /usr/local/bin/kubectl get --raw='/readyz?verbose'
      args:
        executable: /bin/bash
      register: clusterinfo
      retries: 5
      delay: 30
      until: clusterinfo.rc == 0
      changed_when: false
    - name: Show cluster info
      debug:
        var: clusterinfo.stdout_lines
