name: 1. Release

on:
  push:
    tags:
    - v[0-9]+.[0-9]+.[0-9]+
    - v[0-9]+.[0-9]+.[0-9]+-rc[0-9]+

env:
  ENVIRONMENT_RUNS_ON: ubuntu-latest

jobs:
  pre-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Generate release notes
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        prerelease: true
        generate_release_notes: true

  call-offline-build:
    needs: pre-release
    uses: ./.github/workflows/call-offline-build.yaml
    permissions:
      contents: write

  call-images-build:
    uses: ./.github/workflows/call-build-imgs.yaml
    secrets: inherit
    permissions:
      packages: write
      contents: read
    with:
      CI_TYPE: release

  call-os-pkgs-build:
    needs: pre-release
    uses: ./.github/workflows/call-os-pkgs-build.yaml
    secrets: inherit
    permissions:
      packages: write
      contents: write

  call-sha256sum-gen:
    needs: [call-offline-build, call-os-pkgs-build]
    uses: ./.github/workflows/call-sha256sum-gen.yaml
    secrets: inherit
    permissions:
      packages: write
      contents: write

  sync-charts-and-api:
    needs: [call-images-build, call-offline-build, call-os-pkgs-build]
    uses: ./.github/workflows/call-sync-repos.yaml
    secrets: inherit
    permissions:
      packages: write
      contents: read

  generate-release-notes:
    needs: sync-charts-and-api
    uses: ./.github/workflows/call-gen-release-notes.yaml
    secrets: inherit
    permissions:
      contents: write

  build-docs:
    needs: generate-release-notes
    uses: ./.github/workflows/call-build-docs.yaml
    secrets: inherit
    permissions:
      contents: write

  get-environment:
    runs-on: ubuntu-latest
    needs: generate-release-notes
    outputs:
      environment_runs_on: ${{ steps.get_variables.outputs.environment_runs_on }}

    steps:
    - name: Get environment variable
      id: get_variables
      run: |
        echo environment_runs_on=${{ env.ENVIRONMENT_RUNS_ON }} >> $GITHUB_OUTPUT

  call_speedup_offline_packages:
    uses: ./.github/workflows/call-speedup-offline-packags.yaml
    needs: get-environment
    permissions:
      packages: write
      contents: read

  update_kubean_support_matrix:
    uses: ./.github/workflows/update-kubean-support-matrix.yaml
    needs: get-environment
    permissions:
      pull-requests: write
      contents: write
