name: Auto Main CI

on:
  push:
    branches:
      - main

env:
  ENVIRONMENT_RUNS_ON: "self-hosted"
  ENVIRONMENT_CD: "dev"

jobs:
  unit-test:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v3
        with:
          go-version: 1.18.2

      - name: unit test
        run: |
          make test > coverage.temp
          grep total coverage.temp > covarage.txt
          curl -Os https://uploader.codecov.io/latest/linux/codecov
          chmod +x codecov
          ./codecov

  get-spray-ref:
    runs-on: ubuntu-latest
    outputs:
      sha: ${{ steps.get_ref.outputs.sha }}
    steps:
      - name: Get kubespray latest commit sha
        id: get_ref
        run: |
          COMMIT_SHA=`git ls-remote https://github.com/kubernetes-sigs/kubespray.git HEAD | awk '{ print $1}'`
          echo ::set-output name=sha::${COMMIT_SHA}

  call-images-build:
    uses: ./.github/workflows/call-images-build.yaml
    secrets: inherit
    needs: [get-spray-ref, unit-test]
    with:
      spray_ref: ${{ needs.get-spray-ref.outputs.sha }}

  get-environment:
    runs-on: ubuntu-latest
    needs: call-images-build
    outputs:
      environment_runs_on: ${{ steps.get_variables.outputs.environment_runs_on }}
      enviroment_cd: ${{ steps.get_variables.outputs.enviroment_cd }}

    steps:
      - name: Get environment variable
        id: get_variables
        run: |
          echo ::set-output name=environment_runs_on::${{ env.ENVIRONMENT_RUNS_ON }}
          echo ::set-output name=enviroment_cd::${{ env.ENVIRONMENT_CD }}

  call-cd:
    uses: ./.github/workflows/call-cd.yaml
    secrets: inherit
    needs: get-environment
    with:
      ENVIRONMENT_RUNS_ON: ${{ needs.get-environment.outputs.environment_runs_on }}
      ENRIRONMENT_CD: ${{ needs.get-environment.outputs.enviroment_cd }}
