on: workflow_call

env:
  QINIU_SHELL_TAR: qshell-v2.8.0-linux-amd64.tar.gz

jobs:
  upload-qiniu:
    runs-on: self-hosted
    permissions:
      packages: write
      contents: read
    steps:
      - name: clean environment
        run: rm -rf ./*

      - name: Make os packages dir
        run: |
          mkdir -p ${{ github.ref_name }}/

      - name: Download artifact offline-build
        uses: actions/download-artifact@v3
        with:
          name: offline-build
          path: ${{ github.ref_name }}/

      - name: Download artifact os-pkgs-build
        uses: actions/download-artifact@v3
        with:
          name: os-pkgs-build
          path: ${{ github.ref_name }}/os-pkgs/

      - name: Upload tar file to qiniu
        run: |
          ls -lh ${{ github.ref_name }}/
          tar --warning=no-file-changed zcvf kubean-${{ github.ref_name }}.tar.gz ${{ github.ref_name }}/
          wget https://devtools.qiniu.com/$QINIU_SHELL_TAR
          tar -zxvf $QINIU_SHELL_TAR
          mv qshell /usr/local/bin/
          qshell account -w ${{ secrets.QINIU_AK }} ${{ secrets.QINIU_SK }} 'dce-ci'
          echo 'delete the same name of old file'
          qshell delete ${{ secrets.QINIU_BU }} DaoCloud_Enterprise/dce5/kubean-${{ github.ref_name }}.tar.gz
          echo 'upload to qiniu'
          qshell rput ${{ secrets.QINIU_BU }} DaoCloud_Enterprise/dce5/kubean-${{ github.ref_name }}.tar.gz kubean-${{ github.ref_name }}.tar.gz
